### PR TITLE
Add ReproMatch

### PR DESCRIPTION
**Pull request by remram44**
ReproMatch is currently on our internal Gitolite server. Having the source is not enough anyway, since you also have to setup Solr the right way, and get the database content.

But this ReproZip package works (and there is also a Docker image [vidanyu/repromatch](https://hub.docker.com/r/vidanyu/repromatch/)).

### CODE REVIEW

**Comment by fchirigati** [comment]
I would say that the main goal of these examples is to show people how ReproZip can pack different applications. Given the "complexity" of the system (Django + Solr), I think it would be nice to explain how this was packed (including the exact commands), even if the source code is not shared. Would it be possible to add the source code, data, and instructions to set it up, similar to Stacked Up? Maybe we can ask @rexissimus to help us? I think this would be really nice, since people could try both packing and unpacking (a full demo).

**Comment by remram44** [comment]
The source is on our Gitolite, but there's no reason not to put it on ViDA-NYU GitHub. However the setup description is not enough to run it as of now (I had to just copy files off our production server).

I don't know if this needs to be an example. It made sense to try and pack it, we don't have to advertise it I guess.

**Comment by fchirigati** [comment]
I think it makes sense to turn this into a full example, since it is not
too straightforward to pack this type of application. Of course, this
depends on the amount of effort to bring code, data, and scripts (to load
data, for instance) to this repo. But at least a few words on how this was
packed would be nice.

**Comment by remram44** [comment]
Put it on GitHub here: https://github.com/ViDA-NYU/repromatch

**Review by fchirigati — APPROVED** [review]
Looks great! I was also able to successfully reproduce the website!

**Comment by fchirigati** [comment]
Let me first update the main website!

**Comment by fchirigati** [comment]
I guess we need to update the main website in the master branch? This branch does not have the `index.html` file.

**Comment by remram44** [comment]
I added it, please check

**Comment by fchirigati** [comment]
The cards at the bottom row have a different width if compared to the other rows, and different heights between them. Not sure if this can be easily corrected now? Perhaps this can be fixed by #26 ?

**Comment by remram44** [comment]
Yeah this is #26. Feel free to tackle it, I didn't find a better way.

**Pull request merged**
